const AuthActionTypes = {
  SIGN_UP_REQUEST: "AUTH/SIGN_UP_REQUEST",
  SIGN_UP_ERROR: "AUTH/SIGN_UP_ERROR",
  SIGN_UP_SUCCESS: "AUTH/SIGN_UP_SUCCESS",
  SIGN_IN_REQUEST: "AUTH/SIGN_IN",
  SIGN_IN_ERROR: "AUTH/SIGN_IN_ERROR",
  SIGN_IN_SUCCESS: "AUTH/SIGN_IN_SUCCESS",
};

export default AuthActionTypes;
